### ISSUE TITLE
File Locations

### ISSUE THREAD

**Issue by brucek5** [daz3d/DazToC4D#30]
I installed the latest bridge into DAZ using the DAZ Install manager and added the Cinema 4D plugin from GitHub into Cinema 4D my plugin directory.
When I used the DAZ File-> Send To -> Cinema 4D, all the dialogs appear to work, I see it exporting and I get a message box stating its complete.  
When I run the DAZ menu option in Cinema 4D to import I get a model I exported out of DAZ months ago, I removed the "FIG0" directory in the C:\Users\brucek5\Documents\DAZ 3D\Bridges\Daz To Cinema 4D\Exports\FIG\FIG0. When I run the script again in Cinema 4D nothing happens expect the dialog refreshes, but no error and no import. When I restore the "FIG0", the script again reloads and old model. I've removed and restored the Cinema 4D plugin and the DAX menu goes away and re-appears so I know it's finding the latest plugin.

With all this said, it seems to me the Cinema 4D plugin is looking for the DAZ exported files in a location different than where the DAZ plugin is placing it,

Are these paths hard coded or is there a data file(s) that store the exported paths that I could edit? 

FYI - I'm using Cinema 4D R21.

**Comment by danielbui78** [comment]
Thank you for your detailed report.  There may be multiple issues going on, here is a list of things to check to go through them all:

1. Open Daz Studio and select from the main menu: Help -> About Installed Plugins.  Make sure that there is only ONE copy of Daz To Cinema4D Bridge installed, and that the version number is **2022.1.8.19**.  If there are multiple versions or a different version number, then you need to remove all versions and make sure you download and install the latest bugfix here: https://github.com/daz3d/DazToC4D/releases
2. Use the 2022.1.8.19 version of the Daz Studio bridge plugin, and install the Cinema 4D plugin.  Then go inside the plugins folder and find the following file `\DazToC4D\lib\Definitions.py`.  This file should have a date modified stamp of June 18, 2022.  If it is earlier, then make sure you remove all copies of the Cinema 4D bridge plugin and try to install the plugin again.
3. Make sure you delete the "\DAZ 3D\Bridges\Daz To Cinema 4D\Exports\FIG\FIG0" and then try to do a new export from Daz Studio.
4. The reason that the issue with old exports being loaded in the first place, is because the user profile you are using currently has or has had in the past a custom Documents folder, either on a different drive, or somewhere outside of the \Users\username\Documents\ folder, or perhaps you changed your username and it is now in a different \Users\username\Documents\ folder.  Or if you have OneDrive, that can re-direct documents to inside the OneDrive folder.  
 
The Daz Studio plugin uses the Qt4.8 C++ library to read the currently configured Documents folder from the Windows registry / user profile.  The previous versions of the Cinema 4D plugin used a hardcoded method of determining your User folder and then adding on "\Documents" to the end of it.  This will not work if you have a custom Documents folder.  The new 2022.1.8.19 version of the plugin contains a new Definitions.py that was modified by me on June 18, 2022 to fix this issue.  If you are still having problems even after verifying the latest Definitions.py is properly being read by Cinema4D, then please let me know the following:

1. Exact Version and Build # of Windows
2. Path to your User home folder
3. Path to your Documents folder
5. Screenshot of the contents of the Documents\DAZ 3D\Bridges\Daz To Cinema 4D\Exports\FIG\FIG0 folder.
6. Send a copy of the `FIG.dtu` file within that folder.

**Comment by brucek5** [comment]
Hi danielbui78;
Thanks for quick reply!
Before I make changes based on your reply, I wanted to share some additional information.

1. Since the time I installed the first version of the Bridge, all my DAZ content had to be moved to a new hard drive (that has a different path) because storage capacity. 

2.  The older Bridge still appears in the DAZ Script menu, Not sure if you want to modify your "Helper" application to remove any older versions if found. I assume this older plug-in is in some DAZ script directory somewhere,

3. I Noticed your link to Maxon's page on plug-ins. I'm using the older Cinema 4D location method of placing manually installed plug-ins placed in  C:\Users\brucek5\AppData\Roaming\Maxon\Maxon Cinema 4D R21_HIDDEN (HIDDEN is not in my path, I just don't want to publicly share the real numerical value which might be tied to my serial number). I do this because I don't want Cinema 4D plug-ins scattered all over the place making it more difficult to troubleshoot and run backups.

4. Due to size of my computer system, I have dedicated drives based on their function. My C: dive is only for Windows and applications. My E: drive is where my "Documents" are stored. My F: drive is only used for cache (for applications that require caching). My D: drive is used to store 3D files, 3D materials and 3D projects due to the size (this is a 8TB drive) This may be the source of why the Bridge in Cinema 4D is not finding the DAZ exports.

**Comment by danielbui78** [comment]
Sorry -- I think you are misunderstanding me: do **NOT** move your documents or files....

**Comment by brucek5** [comment]
Hi danielbui78,

I think we're on the same page. I have no intention of moving any of my files as getting this Bridge to work is very low on my "priority to work" especially any related to Cinema 4D where I depend on thousands of dollars of software I depend on working.

Maybe in this case, too much information was dangerous. I only provided the additional information in the case something stood out to you that was unique.

I'll keep you posted on my findings. Thanks again, we all appreciate your effort creating this complex tool!  

Bruce Kingsley

**Comment by brucek5** [comment]
Hi danielbui78,

1. I uninstalled the DAZ bridge using the DAZ Install Manager, then re-installed.

2. The DAZ main menu still has a Script->Bridge-> and two DAZ to Cinema 4D menu items, though if I select them the DAZ log has an entry: 2022-06-20 13:38:55.797 [WARNING] :: ..\..\..\..\..\src\sdksource\interface\actions\dzaction.cpp(2152): Could not find script file: "C:/Program Files/DAZ 3D/DAZStudio4/scripts/support/DAZ/Daz to Cinema 4D.dsa"   Not such how to get rid of the code that is creating these menus and the code they are calling.

3.  I added a "Base Genesis 8 Female", then did a File->Send To-> Cinema 4D, No errors, and got a message box stating the export was complete.

4. The Cinema 4D plug-in Definitions.py file is dated June 18, 2022.

5. When I use the plugin in Cinema 4D, I get an error stating it couldn't find a file. This is what was in the Python log:
Traceback (most recent call last):
  File "C:\Users\brucek5\AppData\Roaming\Maxon\Maxon Cinema 4D R21_64C2B3BD\plugins\DazToC4D\lib\DtC4DGuiImportDaz.py", line 310, in Command
    CustomImports().auto_import_genesis(sss_value, normal_value, bump_value)
  File "C:\Users\brucek5\AppData\Roaming\Maxon\Maxon Cinema 4D R21_64C2B3BD\plugins\DazToC4D\lib\CustomImports.py", line 46, in auto_import_genesis
    os.chdir(EXPORT_DIR)
WindowsError: [Error 3] The system cannot find the path specified: u'DAZ 3D\\Bridges\\Daz To Cinema 4D\\Exports'

6.. I found where the DAZ script exported to: E:\Documents\DAZ 3D\Bridges\Daz To Cinema 4D\Exports\FIG\FIG0

 E:\Documents\DAZ 3D was were my content used to be before moving it to a different drive, I checked all the file path definitions in DAZ and don't see anything going to the E: drive, so not sure where the script is getting this path from. I renamed the directory so DAZ can't find it, and DAZ still works properly. But when I run the Send To->, a new DAZ directory is created with all the Bridge files.

**Comment by danielbui78** [comment]
Thank you for sharing the Python log: I see the problem immediately: The script is crashing because it can not resolve your Documents folder path.

You can not find a reference to "E:\Documents\DAZ 3D" anywhere in your DAZ file path definitions because it is not set there.  This is the custom "Documents" folder that I have been alluding to that must be configured within the Windows to exactly where you want the Documents folder to go.  When the Windows Operating System is queried for the "Documents" folder, "E:\Documents\" is the path that it is returning.  In other words, "E:\Documents\" is the official path that the Windows Operating system is recognizing as the Documents folder.

The problem with DazToC4D, is that the Daz Studio plugin is writing to the path that is officially recognized by Windows as the Documents folder for your computer BUT the Cinema4D plugin is not able to resolve the Documents folder.  Because this is failing, the CustomImports.py is trying to connect to the u'DAZ 3D\Bridges\Daz To Cinema 4D\Exports' path, which does not exist since there is no root path to connect to.... give me some time to figure out why the Definitions.py is failing to resolve the Documents path.

**Comment by danielbui78** [comment]
@brucek5, Please try downloading and replacing the Definitions.py in your DazToC4D plugin folder with this one: https://raw.githubusercontent.com/daz3d/DazToC4D/developer/Cinema%204D/appdir_common/plugins/DazToC4D/lib/Definitions.py

I have included a number of error checks to help us understand why the Windows API calls are failing.  The error messages will be printed to the Python Log.  If it completely fails, then the script will default to searching in %USERPROFILE%\Documents.  This will be incorrect for you, but at least the script won't crash and you will at least know where the files are being read.  Please let me know what the output of the Python Log when you are able to test this file.  Thank you

**Comment by danielbui78** [comment]
Sorry for the confusion, I had wrongly assumed Python 3... I will have to look into making changes in the plugin source for Python 2 compatibility.  I will have to do some more in-depth testing and assessment for backward compatibility.  I will get back to you.

**Comment by danielbui78** [comment]
Please try https://github.com/daz3d/DazToC4D/releases/tag/2022.1.9
It should be more compatible with R22 and below

**Comment by brucek5** [comment]
Hi Hi danielbui78,

It works! And wow, very, very impressive plugin!! The Cinema 4D coding is out of this world enabling JCM to be recreated which has never been possible before.  You're one hell of a programmer, I tried different characters, animations, and everything works!.

Thanks a lot!  Bruce Kingsley.
Issue closed,
