### ISSUE TITLE
Manual installing to Daz studio. 

### ISSUE THREAD

**Issue by sherbasergei** [daz3d/DazToC4D#51]
Hey.
Issue: Don't understand how to and cant find way for manual install script to daz3d.

With installing to cinema I don't have any issues. It's already work.

In Daz I see script in "scrips"  folder in content library. But I don't see it in "send to" menu. 

Is it right that I need to press f3 and make action? OK. I know it, but can't do it. 

So if you have a little bit time could you add more Detailed instructions to Readme or into repository

Thank you very much and have a good day!

**Comment by danielbui78** [comment]
Sorry, are you asking how to specifically install an old version of the Daz to Cinema4D Bridge released prior to June 2022?  It sounds like you are mixing up features and items from the latest Bridge with things from older, outdated versions.  Please clarify exactly what it is you are trying to do and with what version of the Bridge you wish to use, otherwise it's not possible for me to give you an answer that would help you.

If you are trying to use the latest Daz to Cinema4D Bridge, then it should be located in the File menu under the Send To submenu.  The "Scripts" menu is only for the old version and if Daz to Cinema4D Bridge exists there, then it means you are using an old, outdated version of the Bridge.  If you have customized your menu before and have previously installed a version of the Daz to Cinema4D bridge prior to June 2022, then the "Scripts" menu may still be left over.  This is okay and will not affect your ability to use the new bridge, as long as it is installed correctly.

The latest versions of the Daz to Cinema4D Bridge use a .DLL plugin file and not a script in Daz Studio.  To manually install a DLL plugin to Daz Studio, please refer to this video: https://www.youtube.com/watch?v=LDDPfygZfgs

If after following the steps above and verifying that the DLL plugin for the Daz to Cinema4D bridge is enabled in the "About Installed Plugins" window, then let me know and we can try to troubleshoot the issue.

**Comment by sherbasergei** [comment]
Ahhh, i see. I`m stupid. So now i already installed plugind to Daz and C4D. But the last one problem is C4D don`t see exported files. This screenshot 
![image](https://user-images.githubusercontent.com/85226981/229804863-a16079ea-c1e0-4157-9cff-32d7a3d23aa7.png) Even though in Daz plugin tell me that everything is okay

**Comment by sherbasergei** [comment]
Omg! You are the best! Thank you very much! Have a good day!
